test = 'vender/test.html'
vender_center = 'vender/all-downloads.html'
designers_collection = 'vender/collection-designers.html'
works_collection = 'vender/collection-works.html'
set_account = 'vender/account-setup.html'
